---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: |
            .circleci/greenkeeper
            yarn add -D nyc@11 @oclif/nyc-config@1
      - run:
          name: Testing
          command: $NYC yarn test
      - run:
          name: Submitting code coverage to codecov
          command: |
            $NYC report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
  node-8:
    <<: *test
    docker:
      - image: node:8
  
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - attach_workspace: {at: node_modules}
      - run: ./.circleci/setup_git
      - run: ./.circleci/release

workflows:
  version: 2
  new_test_plugins:
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
